version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DEBUG=True
      - ENVIRONMENT=development
    command: uvicorn backend.api.app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend